#!/bin/bash -e
mkdir -p /run/fedora-networking
cd /run/fedora-networking

DESTINATION="${DESTINATION:-localhost}"

cat <<EOF >> /etc/raddb/users
testUser    Cleartext-Password := "hello"
            Reply-Message := "Hello, %{User-Name}"
EOF

sed -i "s/ipaddr\s*= .*/ipaddr = */" /etc/raddb/clients.conf

sed -i "s/ipaddr\s*= .*/ipaddr = $DESTINATION/" /etc/raddb/sites-enabled/default

exec `which radiusd` -X
