#!/bin/bash -e

mkdir -p /run/fedora-networking
cd /run/fedora-networking

mkdir -p /var/ftp/pub
echo "Hello World!" > /var/ftp/pub/test.file

cat <<EOF > rsyncd.conf

 [ftp]
        path = /var/ftp/pub
        comment = ftp export area
EOF

exec `which rsync` --daemon --config=/run/fedora-networking/rsyncd.conf --port=32999
