#!/bin/bash -e
mkdir -p /run/fedora-networking
/usr/bin/cp -u dummy.spec /run/fedora-networking/
cd /run/fedora-networking

rpmbuild --define "_topdir /var/run/fedora-networking" -ba dummy.spec

mkdir -p /var/ftp/pub/fedora-networking

/usr/bin/cp -u \
    /var/run/fedora-networking/RPMS/noarch/dummy-rpm-1.0-1.noarch.rpm \
    /var/ftp/pub/fedora-networking

cd /var/ftp/pub/

createrepo fedora-networking

cd /run/fedora-networking

exec `which vsftpd`
